### ISSUE TITLE
Header row missing in tables

### ISSUE THREAD

**Issue by uwereiter** [divinity666/ruby-grafana-reporter#7] opened 2021-06-28 10:59 UTC
Hi,

I'm using the reporter 0.4.3 from raspberry or Windows against a Grafana 7.5.3 to report graphs and tables.

For tables I tried both grafana_sql_table and grafana_panel_query_table. These are showing the data as expected, but both do not show the header row with field names or aliases.

Is that a know bug in the reporter? Or do I have to activate somewhere else that tables show a header?

Best regards
Uwe

**Comment by divinity666** [comment] 2021-06-28 20:06
Dear Uwe,

thanks for your question. It is true: Currently the table requests do not return the header values (though they are available internally).

Today the only option is, to specify the header manually in your template. This is by design.

Anyway  I have been thinking about an option, which could be used to output also the header. I will investigate for one of the next versions.

Best regards
Christian

**Comment by divinity666** [comment] 2021-07-12 22:15
This is now fixed in release 0.4.4 with the option `include_headline="true"` in the table SQL calls

Check it out!

**Closed by divinity666** 2021-07-12 22:15 UTC
