### ISSUE TITLE
Error to configure a report in grafana

### ISSUE THREAD

**Issue by JERUSO** [divinity666/ruby-grafana-reporter#38] opened 2023-01-31 19:39 UTC
**Describe the issue**
I have configured the reporter service in a linux centos, it generates the demo report without problem, however following the documentation I have created a variable in my report.

![image](https://user-images.githubusercontent.com/19862601/215863393-70089fe2-b598-4318-b94d-6eaeb58ca45d.png)

I have created the variable as a constant and as a text and I have entered the name of the grafana dashboard.

The link configuration in the dashboard grafana it is.
![image](https://user-images.githubusercontent.com/19862601/215863709-cbc6c2a7-3ebd-4805-8daa-e793a1e6fc23.png)

When Running it shows me the following error
![image](https://user-images.githubusercontent.com/19862601/215863879-eab72669-ea76-4421-857c-e2cdaaa60ffa.png)

**Application call**
I do the application call as shown
![image](https://user-images.githubusercontent.com/19862601/215864071-0bae9034-9b38-4b79-9d77-d93911110c25.png)

**Environment (please complete the following information):**
 - OS [e.g. Windows 10]:  
 - Grafana version [e.g. 6.3.4]: 9.0.2
 - Environment [e.g. source, gem, docker or windows-exe]: gem
 - Ruby Version, if source or gem environment [e.g. 2.3.7]: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]
 - Reporter version [e.g. 0.3.0]: lastest
 
How do I be able to call the report for each one of the dashboards? Is there a portal with examples? I just followed the github documentation.

Thanks

**Comment by divinity666** [comment] 2023-02-05 18:42
Thanks for using the reporter.

So, it looks like, you try to have a variable in your dashboard, which points to the reporter template name. In your configuration, you point to a template named ˋVMwarevSphere_Overviewˋ, but obviously this file does not exists, as you can see in the log entries.

The ˋtemplateˋ variable has to point to the template file name, not to the dashboard. If you want to configure a template for a dashboard, you have to simply use the functions, e.g. ˋgrafana_sql_tableˋ with the option ˋdashboardˋ etc., to configure it properly.

I strongly recommend digging deeper in the wizard template file, which should make thinks a bit clearer.

Feel free to get back in case of questions.

**Comment by Med-salem-Guenaya** [comment] 2024-05-18 04:00
hello. i did the same but got the same error. now i understand the problem is the lack of a template file.
that being said how do i make this template file and what can i include in it to make it render the graphs in my grafana web view?

sorry if this has already been answered somewhere else.

**Comment by divinity666** [comment] 2024-05-18 08:28
Try creating a report template as described here: [https://github.com/divinity666/ruby-grafana-reporter?tab=readme-ov-file#quick-start](url)

Then you should be able to render that template with the reporter.

After that succeeds, you should be able to go through the template file and create your own, or adapt the demo report as needed to get to the desired result.

**Comment by divinity666** [comment] 2024-07-13 14:20
Closing because of missing feedback.

**Closed by divinity666** 2024-07-13 14:20 UTC
